### ISSUE TITLE
AccessViolationException when runas system

### ISSUE THREAD

**Issue by johnny-witt** [EasyHook/EasyHook#103]
Hi there - I'm pretty new to all this hooking stuff so please bare with me. :-)

Although its only mentioning runas administrators in the documentation. There are support for multiple sids. So I've tried to setup a runas SYSTEM. And SYSTEM should have the correct rights to inject the DLL.

My situation is that I install Client program running as current user doing a lot of other stuff. Occasionally a process are required to be monitored. This Client program sends the instructions (and receive data) from a separate IPC between Client Program and RemoteMon (running as system) this works fine. RemoteMon (as SYSTEM) then sets up its own IPC channels between RemoteMon and the DLL as documented. 

Easyhook in use are the latest from Nuget : version 2.7.5870.9 and .NET 4.0+ is used. 

Everything works fine when the RemoteMon is run as administrator on both Windows 10 and Windows 7. And I actually got it working perfect on Windows 10 ... with a normal user running the client program and All Easyhook running as system.

However on windows 7 I get :
There was an error while connecting to target:
System.AccessViolationException: STATUS_ACCESS_DENIED: Unable to create remote thread. (Code: 8)

Server stack trace:
   at EasyHook.NativeAPI.Force(Int32 InErrorCode)
   at EasyHook.RemoteHooking.InjectEx(Int32 InHostPID, Int32 InTargetPID, Int32 InWakeUpTID, Int32 InNativeOptions, String InLibraryPath_x86, String InLibraryPa
th_x64, Boolean InCanBypassWOW64, Boolean InCanCreateService, Boolean InRequireStrongName, Object[] InPassThruArgs)
   at EasyHook.HelperServiceInterface.InjectEx(Int32 InHostPID, Int32 InTargetPID, Int32 InWakeUpTID, Int32 InNativeOptions, String InLibraryPath_x86, String In
LibraryPath_x64, Boolean InCanBypassWOW64, Boolean InCanCreateService, Boolean InRequireStrongName, Object[] InPassThruArgs)
   at System.Runtime.Remoting.Messaging.StackBuilderSink._PrivateProcessMessage(IntPtr md, Object[] args, Object server, Object[]& outArgs)
   at System.Runtime.Remoting.Messaging.StackBuilderSink.SyncProcessMessage(IMessage msg)

Exception rethrown at [0]:
   at System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
   at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
   at EasyHook.HelperServiceInterface.InjectEx(Int32 InHostPID, Int32 InTargetPID, Int32 InWakeUpTID, Int32 InNativeOptions, String InLibraryPath_x86, String In
LibraryPath_x64, Boolean InCanBypassWOW64, Boolean InCanCreateService, Boolean InRequireStrongName, Object[] InPassThruArgs)
   at EasyHook.RemoteHooking.InjectEx(Int32 InHostPID, Int32 InTargetPID, Int32 InWakeUpTID, Int32 InNativeOptions, String InLibraryPath_x86, String InLibraryPa
th_x64, Boolean InCanBypassWOW64, Boolean InCanCreateService, Boolean InRequireStrongName, Object[] InPassThruArgs)
   at EasyHook.RemoteHooking.Inject(Int32 InTargetPID, InjectionOptions InOptions, String InLibraryPath_x86, String InLibraryPath_x64, Object[] InPassThruArgs)
   at FileMonitor.FileMonIpcServer.hook(UInt32 pid) in FileMonitor Module\Analyser.cs:line 135

Looks like setting up using different SID doesn't influence the situation (unless using NullSid)
The code involved is :
// IPC create : 

RemoteHooking.IpcCreateServer<FileMonInterface>(ref ChannelName, WellKnownObjectMode.SingleCall, WellKnownSidType.WorldSid);

//Inject:

                RemoteHooking.Inject(
                    (Int32)pid,
                    "FileMonitor.dll",
                    "FileMonitor.dll",
                    ChannelName);

I've tried injection options : InjectionOptions.DoNotRequireStrongName, and other changes but as it still only works when runas administrator, I'm not sure that would have any influence anyway. I've tried to setup different try catch but the only reported exception is in the Remotehooking.inject.

As it works on windows 10 (64bit)  - I should expect is to be working on windows 7 ?

I'm running out of ideas to try ? Any thoughts ?

**Comment by spazzarama** [comment]
@johnny-witt so is the app that is doing the injection running under a different session? Is so you may need to look at patching EasyHook to use NtCreateThreadEx as shown here: https://github.com/CodeTickler/EasyHook/commit/604aa83c515e109b39125d6c50a3605c28a76fc7

**Comment by spazzarama** [comment]
@johnny-witt is the app you are injecting from running as admin?

**Comment by maximumgame** [comment]
I have the same issue on windows 10 pro. Seems to work fine in .net 3.5 weirdly.

**Comment by spazzarama** [comment]
Any chance you can provide a simple project to reproduce this problem?
