### ISSUE TITLE
How to rename the easyhook's dll ?

### ISSUE THREAD

**Issue by SocialShutdown** [EasyHook/EasyHook#113]
Hello, i have a project using the easyhook nuget package. And i'm trying to rebuild easyhook with different dll names. I do credit easyhook for the licence but I don't want everyone to know witch dll is involved easyhook, i would like to rename them (just example) : 1.dll (easyhook.dll), 2.dll (easyhook32.dll), 3.dll (easyhook64.dll), 4.dll (easyload32.dll) and 5.dll (easyload64.dll).

However, the referencies in my project only point on %project%\packages\EasyHook.2.7.5870.9\lib\net40\EasyHook.dll. No path is given to the dependencies located in %project%\packages\EasyHook.2.7.5870.9\content\net40 .

How do you properly rename the assemblies of a nuget package ? Is there another solution ?

**Comment by spazzarama** [comment]
Just manually add the references to your project, with a few minor changes to code you can even use ILMerge. Thinking about it you might need to do a custom build anyway for Easyhook32/64 and so on.

**Comment by SocialShutdown** [comment]
I got those kind of errors when injecting : 
2:44:45  : There was an error while connecting to target:
System.ApplicationException: STATUS_INTERNAL_ERROR: Unknown error in injected C++ completion routine. (Code: 15)
   at EasyHook.NativeAPI.Force(Int32 InErrorCode)
   at EasyHook.RemoteHooking.InjectEx(Int32 InHostPID, Int32 InTargetPID, Int32 InWakeUpTID, Int32 InNativeOptions, String InLibraryPath_x86, String InLibraryPath_x64, Boolean InCanBypassWOW64, Boolean InCanCreateService, Boolean InRequireStrongName, Object[] InPassThruArgs)
   at Project.Program.Main(String[] args)
Or else : 
3:03:25  : There was an error while connecting to target:
System.ArgumentException: STATUS_INVALID_PARAMETER_4: The given 32-Bit library does not exist! (Code: 2)
   at EasyHook.NativeAPI.Force(Int32 InErrorCode)
   at EasyHook.RemoteHooking.InjectEx(Int32 InHostPID, Int32 InTargetPID, Int32 InWakeUpTID, Int32 InNativeOptions, String InLibraryPath_x86, String InLibraryPath_x64, Boolean InCanBypassWOW64, Boolean InCanCreateService, Boolean InRequireStrongName, Object[] InPassThruArgs)
   at Project.project.Main(String[] args)

I don't use/rename and copy in the execution folder the svc executalbes (easyhook32svc.exe, etc), i thought the were not usefull. Is it an issue ?

**Comment by SocialShutdown** [comment]
ILMerge don't work for unmanaged code, so i can't merge all easyhook dll's with it. I also don't understand how easyhook rename the easyload dll assembly to easyhook32.dll and easyhook64.dll.
The configuration assembly name is easyload.dll and there is no pos build command in this project.

**Comment by spazzarama** [comment]
@SocialShutdown the easyhook32/64 are specified in the project file under the different build targets (open the project file in an editor and you will see it). You will have to edit any hard coded assembly names that might be used to rename.

```
    <TargetName Condition="'$(Configuration)|$(Platform)'=='netfx3.5-Debug|Win32'">EasyHook32</TargetName>
    <TargetName Condition="'$(Configuration)|$(Platform)'=='netfx4-Debug|Win32'">EasyHook32</TargetName>
    <TargetName Condition="'$(Configuration)|$(Platform)'=='netfx3.5-Debug|x64'">EasyHook64</TargetName>
    <TargetName Condition="'$(Configuration)|$(Platform)'=='netfx4-Debug|x64'">EasyHook64</TargetName>
    <TargetName Condition="'$(Configuration)|$(Platform)'=='netfx3.5-Release|Win32'">EasyHook32</TargetName>
    <TargetName Condition="'$(Configuration)|$(Platform)'=='netfx4-Release|Win32'">EasyHook32</TargetName>
    <TargetName Condition="'$(Configuration)|$(Platform)'=='netfx3.5-Release|x64'">EasyHook64</TargetName>
    <TargetName Condition="'$(Configuration)|$(Platform)'=='netfx4-Release|x64'">EasyHook64</TargetName>
```
