### ISSUE TITLE
STATUS_NO_MEMORY: Unable to allocate memory in target process. (Code: 5)

### ISSUE THREAD

**Issue by polil91** [EasyHook/EasyHook#120]
Hello guys, 
I am using easyhook to hook some win32 interfaces on user running applications.
I have been sucessfully injecting most of the applications except some that seem to have a kind of memory protection.

The specific error I get is the following: 
Exception thrown: 'System.OutOfMemoryException' in EasyHook.dll
STATUS_NO_MEMORY: Unable to allocate memory in target process. (Code: 5)
   at EasyHook.NativeAPI.Force(Int32 InErrorCode)
   at EasyHook.RemoteHooking.InjectEx(Int32 InHostPID, Int32 InTargetPID, Int32 InWakeUpTID, Int32 InNativeOptions, String InLibraryPath_x86, String InLibraryPath_x64, Boolean InCanBypassWOW64, Boolean InCanCreateService, Boolean InRequireStrongName, Object[] InPassThruArgs)
   at EasyHook.RemoteHooking.Inject(Int32 InTargetPID, InjectionOptions InOptions, String InLibraryPath_x86, String InLibraryPath_x64, Object[] InPassThruArgs)
  
I read in a codeproject question that it can be bypassed using this technique:
http://www.codeproject.com/Questions/714991/Allocate-Memory-in-Target-Process

But I do not want to mess with easyhook libraries.
Is there another way to inject on those applications?

I already tried to mess around with inject options but with no luck.

I use .net 4 binary libraries that are precompiled by you. ( I get the same error with the binaries built by me too).

Any help would be most welcome.

Thanks a lot.

Ilias P.

**Comment by spazzarama** [comment]
This really depends upon which application and why you are getting an "ERROR_ACCESS_DENIED".

You may need to provide more details about the target process, is it running in the same session?, is it a desktop app?, is it a process with limited security (e.g. some chrome processes are running in a limited security context that prevent a lot of operations working).

**Comment by Arrianos** [comment]
I see the same issue. Happens with the target process Apex Legends game, which is being protected by Easy anti-cheat - unsure if that's the cause for the issue. Otherwise, the process is in the same user session as the caller of EasyHook as well. At the same time, OBS studio attaches its hook just fine for that game.
Any idea on the possible workaround?
