### ISSUE TITLE
IsBadReadPtr or Code 5 or Code 15 on hooking SQL Server

### ISSUE THREAD

**Issue by kozhevnikov** [EasyHook/EasyHook#140]
There seems to be a few issues regarding codes 5 and 15, but few include repeatable reproduction steps. I'm running a vanilla VM with [Windows 10 x64](https://www.microsoft.com/en-gb/software-download/windows10ISO) and [SQL Server 2016](https://www.microsoft.com/en-gb/cloud-platform/sql-server-editions-developers) (both ISOs available publicly) and trying to hook `sqlservr.exe` process. All precompiled tools fail with either code 5, 15 or with IsBadReadPtr under both NetFX3.5 and NetFX4.0.

TestFuncHooks.exe

```
---------------------------
TestFuncHooks.exe - Fatal Application Exit
---------------------------
memory.c - !IsBadReadPtr(InPtr, InSize) 
```

ProcessMonitor.exe

```
---------------------------
An error has occurred...
---------------------------
STATUS_INTERNAL_ERROR: Unknown error in injected C++ completion routine. (Code: 15)
```

FileMon.exe

```
System.ApplicationException: STATUS_INTERNAL_ERROR: Unable to find EasyHook library in target process context. (Code: 5)

Server stack trace:
   at EasyHook.NativeAPI.Force(Int32 InErrorCode)
   at EasyHook.RemoteHooking.InjectEx(Int32 InHostPID, Int32 InTargetPID, Int32 InWakeUpTID, Int32 InNativeOptions, String InLibraryPath_x86, String InLibraryPath_x64, Boolean InCanBypassWOW64, Boolean InCanCreateService, Boolean InRequireStrongName, Object[] InPassThruArgs)
   at System.Runtime.Remoting.Messaging.StackBuilderSink._PrivateProcessMessage(IntPtr md, Object[] args, Object server, Object[]& outArgs)
   at System.Runtime.Remoting.Messaging.StackBuilderSink.SyncProcessMessage(IMessage msg)

Exception rethrown at [0]:
   at System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
   at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
   at EasyHook.HelperServiceInterface.InjectEx(Int32 InHostPID, Int32 InTargetPID, Int32 InWakeUpTID, Int32 InNativeOptions, String InLibraryPath_x86, String InLibraryPath_x64, Boolean InCanBypassWOW64, Boolean InCanCreateService, Boolean InRequireStrongName, Object[] InPassThruArgs)
   at EasyHook.RemoteHooking.InjectEx(Int32 InHostPID, Int32 InTargetPID, Int32 InWakeUpTID, Int32 InNativeOptions, String InLibraryPath_x86, String InLibraryPath_x64, Boolean InCanBypassWOW64, Boolean InCanCreateService, Boolean InRequireStrongName, Object[] InPassThruArgs)
   at FileMon.Program.Main(String[] args)
```

**Comment by spazzarama** [comment]
@kozhevnikov can you please try when running as administrator? I don't currently have time to setup a VM for this.
