### ISSUE TITLE
Unable to hook Trusted Windows Apps - STATUS_INTERNAL_ERROR - Code 5

### ISSUE THREAD

**Issue by r89m** [EasyHook/EasyHook#199]
Hi,

I am attempting to use the tutorial project RemoteFileMonitor to monitor a Trusted Windows App (eg Calculator), but am getting a STATUS_INTERNAL_ERROR with Code 5. This happens both when run as a normal user or as an administrator.

The RemoteFileMonitor demo project works fine with standard Desktop App, such as Notepad++.

I am able to monitor API calls using API Monitor v2.

Do you have any advice as to how I might be able to hook into these Trusted Applications?

Many thanks,

Richard

Full stack trace for reference
```
Usage: FileMonitor ProcessID
   or: FileMonitor PathToExecutable

e.g. : FileMonitor 1234
          to monitor an existing process with PID 1234
  or : FileMonitor "C:\Windows\Notepad.exe"
          create new notepad.exe process using RemoteHooking.CreateAndInject

Enter a process Id or path to executable
> 15336

Attempting to inject into process 15336
There was an error while injecting into target:
System.ApplicationException: STATUS_INTERNAL_ERROR: Unable to find EasyHook library in target process context. (Code: 5)

Server stack trace:
   at EasyHook.NativeAPI.Force(Int32 InErrorCode)
   at EasyHook.RemoteHooking.InjectEx(Int32 InHostPID, Int32 InTargetPID, Int32 InWakeUpTID, Int32 InNativeOptions, String InLibraryPath_x86, String InLibraryPath_x64, Boolean InCanBypassWOW64, Boolean InCanCreateService, Boolean InRequireStrongName, Object[] InPassThruArgs)
   at EasyHook.HelperServiceInterface.InjectEx(Int32 InHostPID, Int32 InTargetPID, Int32 InWakeUpTID, Int32 InNativeOptions, String InLibraryPath_x86, String InLibraryPath_x64, Boolean InCanBypassWOW64, Boolean InCanCreateService, Boolean InRequireStrongName, Object[] InPassThruArgs)
   at System.Runtime.Remoting.Messaging.StackBuilderSink._PrivateProcessMessage(IntPtr md, Object[] args, Object server, Object[]& outArgs)
   at System.Runtime.Remoting.Messaging.StackBuilderSink.SyncProcessMessage(IMessage msg)

Exception rethrown at [0]:
   at System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
   at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
   at EasyHook.HelperServiceInterface.InjectEx(Int32 InHostPID, Int32 InTargetPID, Int32 InWakeUpTID, Int32 InNativeOptions, String InLibraryPath_x86, String InLibraryPath_x64, Boolean InCanBypassWOW64, Boolean InCanCreateService, Boolean InRequireStrongName, Object[] InPassThruArgs)
   at EasyHook.RemoteHooking.InjectEx(Int32 InHostPID, Int32 InTargetPID, Int32 InWakeUpTID, Int32 InNativeOptions, String InLibraryPath_x86, String InLibraryPath_x64, Boolean InCanBypassWOW64, Boolean InCanCreateService, Boolean InRequireStrongName, Object[] InPassThruArgs)
   at EasyHook.RemoteHooking.Inject(Int32 InTargetPID, String InLibraryPath_x86, String InLibraryPath_x64, Object[] InPassThruArgs)
   at FileMonitor.Program.Main(String[] args) in D:\GitHub\EasyHook-Tutorials\Managed\RemoteFileMonitor\FileMonitor\Program.cs:line 65
<Press any key to exit>
```

**Comment by spazzarama** [comment]
Currently EasyHook doesn't work around the issues with loading libraries into trusted apps (I believe LoadLibrary will not work with arbitrary paths?)

Will have to mark this as an feature request.

Cheers, J

**Comment by r89m** [comment]
Thanks a lot for your speedy response Justin, it's much appreciated.

To be honest I'm fairly new to DLL injection - what sort of complexity would be involved in implementing this feature?

**Comment by r89m** [comment]
Hi Justin,

I've had a fairly unskilled attempt at resolving this (including moving DLLs to System32 and some other suggestions I saw online) without much luck.

Would you be able to give me some idea as to what we be involved in implementing this change within the EasyHook code base? Depending on the complexity I could either submit a pull request or put a bounty on this issue. 

Cheers,

Richard

**Comment by spazzarama** [comment]
Code 5: refers to Win32 Errorcode 5 (Access Denied).

I would be stepping through the injection process to determine exactly what operation is failing.
