### ISSUE TITLE
Failed to connect to an IPC Port: The system cannot find the file specified.

### ISSUE THREAD

**Issue by fexxx** [EasyHook/EasyHook#205]
Some users of my application are experiencing an issue with IPC setup with EasyHook. The error is detailed below.

Other users are experiencing no problems at all and so I guess this could be a permissions error where the user does not have permission to set up named pipe IPC?

What would be the best steps to diagnose / resolve? Are there minimal requirements for IPC?

Thank you

```
System.Runtime.Remoting.RemotingException: Failed to connect to an IPC Port: The system cannot find the file specified.
 

Server stack trace: 
   at System.Runtime.Remoting.Channels.Ipc.IpcPort.Connect(String portName, Boolean secure, TokenImpersonationLevel impersonationLevel, Int32 timeout)
   at System.Runtime.Remoting.Channels.Ipc.ConnectionCache.GetConnection(String portName, Boolean secure, TokenImpersonationLevel level, Int32 timeout)
   at System.Runtime.Remoting.Channels.Ipc.IpcClientTransportSink.ProcessMessage(IMessage msg, ITransportHeaders requestHeaders, Stream requestStream, ITransportHeaders& responseHeaders, Stream& responseStream)
   at System.Runtime.Remoting.Channels.BinaryClientFormatterSink.SyncProcessMessage(IMessage msg)

Exception rethrown at [0]: 
   at System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
   at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
```

**Comment by spazzarama** [comment]
Pretty sure a permission issue will give you an access denied message.

I would debug further to determine that the channel is actually open, it doesn't sound like an issue with EasyHook. Perhaps a simple test app(s) that setup and use IPC as a sanity check?

Cheers,
Justin
