### ISSUE TITLE
not working winixp sp3

### ISSUE THREAD

**Issue by MisterChangRay** [EasyHook/EasyHook#311]
i try to hook OpenProcess in win7x64&win7x32&winxp;
code working on win7 is fine, but winxp is not working ;

use remoteInject

exception:
   at EasyHook.NativeAPI_x86.RhInjectLibrary(Int32 InTargetPID, Int32 InWakeUpTID, Int32 InInjectionOptions, String InLibraryPath_x86, String InLibraryPath_x64, IntPtr InPassThruBuffer, Int32 InPassThruSize)
   at EasyHook.NativeAPI.RhInjectLibraryEx(Int32 InTargetPID, Int32 InWakeUpTID, Int32 InInjectionOptions, String InLibraryPath_x86, String InLibraryPath_x64, IntPtr InPassThruBuffer, Int32 InPassThruSize)
   at EasyHook.RemoteHooking.InjectEx(Int32 InHostPID, Int32 InTargetPID, Int32 InWakeUpTID, Int32 InNativeOptions, String InLibraryPath_x86, String InLibraryPath_x64, Boolean InCanBypassWOW64, Boolean InCanCreateService, Boolean InRequireStrongName, Object[] InPassThruArgs)
   at EasyHook.RemoteHooking.Inject(Int32 InTargetPID, String InLibraryPath_x86, String InLibraryPath_x64, Object[] InPassThruArgs)
   at MouseKeyHook.MouseKeyHook.MouseHookProc(Int32 nCode, Int32 wParam, IntPtr lParam) in C:\Users\Zr\Documents\SharpDevelop Projects\screen-lock\MouseHook.cs:line 209

**Comment by MisterChangRay** [comment]
i try to test release version EasyHook 2.7 Beta (2.7.5558.0);
this package can work in winxp ;
