### ISSUE TITLE
Having trouble running FileMon example in the source code

### ISSUE THREAD

**Issue by zaidalyafeai** [EasyHook/EasyHook#52]
I'm having a trouble running the FileMon example. I downloaded the EasyHook source code and built the EasyHook.sln file. Then when I start the FileMon file with a specific process id it gives me the following exception 

```
Usage: FileMon %PID%
   or: FileMon PathToExecutable

Please enter a process Id or path to executable: 7724
There was an error while connecting to target:
System.ComponentModel.Win32Exception (0x80004005): The system cannot find the file specified
   at System.Diagnostics.Process.StartWithShellExecuteEx(ProcessStartInfo startInfo)
   at EasyHook.WOW64Bypass.Install() in c:\Users\USER\Desktop\EasyHook-master\EasyHook\WOW64Bypass.cs:line 80
   at EasyHook.WOW64Bypass.Inject(Int32 InHostPID, Int32 InTargetPID, Int32 InWakeUpTID, Int32 InNativeOptions, String InLibraryPath_x86, String InLibraryPath_x64, Boolean InRequireStrongName, Object[] InPassThruArgs) in c:\Users\USER\Desktop\EasyHook-master\EasyHook\WOW64Bypass.cs:line 104
   at EasyHook.RemoteHooking.InjectEx(Int32 InHostPID, Int32 InTargetPID, Int32 InWakeUpTID, Int32 InNativeOptions, String InLibraryPath_x86, String InLibraryPath_x64, Boolean InCanBypassWOW64, Boolean InCanCreateService, Boolean InRequireStrongName, Object[] InPassThruArgs) in c:\Users\USER\Desktop\EasyHook-master\EasyHook\RemoteHook.cs:line 689
   at EasyHook.RemoteHooking.Inject(Int32 InTargetPID, String InLibraryPath_x86, String InLibraryPath_x64, Object[] InPassThruArgs) in c:\Users\USER\Desktop\EasyHook-master\EasyHook\RemoteHook.cs:line 544
   at FileMon.Program.Main(String[] args) in c:\Users\USER\Desktop\EasyHook-master\Examples\FileMon\Program.cs:line 78
<Press any key to exit>

```

What could be the root of this problem, I'm running windows 10 with visual studio 2013 if that helps. 

Thanks

**Comment by spazzarama** [comment]
You need the EasyHook32/64svc.exe files in the same directory also. As well as EasyLoad32/64.dll

**Comment by zaidalyafeai** [comment]
Hey spazzarama, thanks for your reply. These files are in the binaries provided to download, right? I extracted the folders NetFX3.5/4 to the EasyHook-master folder but nothing worked. What do you mean by the "same directory"? 

I am new to these things, thanks for the help!

**Comment by zaidalyafeai** [comment]
Hey spazzarama, thanks for your reply. These files are in the binaries provided to download, right? I extracted the folders NetFX3.5/4 to the EasyHook-master folder but nothing worked. What do you mean by the "same directory"? 

I am new to these things, thanks for the help!

**Comment by spazzarama** [comment]
At runtime it will try to run the following process:
```
(EasyHook.Config.DependencyPath.Length > 0 ? EasyHook.Config.DependencyPath : EasyHook.Config.GetProcessPath()) + EasyHook.Config.GetWOW64BypassExecutableName()
```

To double check where you need the files, run the above within the debugger's Immediate Window while within a breakpoint before injection.

**Comment by spazzarama** [comment]
I mean the same directory where FileMon.exe is located.

**Comment by spazzarama** [comment]
@zaidalyafeai  is this still an issue?

**Comment by zaidalyafeai** [comment]
@spazzarama, I fixed the problem as you suggested :)
