### ISSUE TITLE
An issue while injecting some processes

### ISSUE THREAD

**Issue by zaidalyafeai** [EasyHook/EasyHook#54]
I've made some adjustments to the example provided in the source code to intercept some functions in the "ws2_32.dll" library. I've made some server/client program and it works perfectly. When I try to inject some processes in the system like chrome.exe I get the following error 
```
There was an error while connecting to target:
System.ApplicationException: STATUS_INTERNAL_ERROR: Unable to find EasyHook library in target process context. (Code: 5)
   at EasyHook.NativeAPI.Force(Int32 InErrorCode) in c:\Users\USER\OneDrive\151\ICS 411\project\testing\EasyHook-master\EasyHook\DllImport.cs:line 480
   at EasyHook.RemoteHooking.InjectEx(Int32 InHostPID, Int32 InTargetPID, Int32 InWakeUpTID, Int32 InNativeOptions, String InLibraryPath_x86, String InLibraryPath_x64, Boolean InCanBypassWOW64, Boolean InCanCreateService, Boolean InRequireStrongName, Object[] InPassThruArgs) in c:\Users\USER\OneDrive\151\ICS 411\project\testing\EasyHook-master\EasyHook\RemoteHook.cs:line 728
   at FileMon.Program.Main(String[] args) in c:\Users\USER\OneDrive\151\ICS 411\project\testing\EasyHook-master\Examples\FileMon\Program.cs:line 81
```

**Comment by spazzarama** [comment]
Can you try other instances of chrome.exe as well please (i.e. there are usually at least 2)? I have found that some of the chrome processes appear to prevent dll injection.

**Comment by uGiFarukh** [comment]
Was wondering how those chrome process prevents dll injection? I never heard of that. What could be the smartest way to prevent process dll injection in C# justin?

**Comment by hatRiot** [comment]
Seeing this when attempting to hook kernel32!WriteFile in a running x86 process on x64 Windows 7.  

```
Error injecting: System.ApplicationException: STATUS_INTERNAL_ERROR: Unable to find EasyHook library in target process c
ontext. (Code: 5)

Server stack trace:
   at EasyHook.NativeAPI.Force(Int32 InErrorCode)
   at EasyHook.RemoteHooking.InjectEx(Int32 InHostPID, Int32 InTargetPID, Int32 InWakeUpTID, Int32 InNativeOptions, Stri
ng InLibraryPath_x86, String InLibraryPath_x64, Boolean InCanBypassWOW64, Boolean InCanCreateService, Boolean InRequireS
trongName, Object[] InPassThruArgs)
   at EasyHook.HelperServiceInterface.InjectEx(Int32 InHostPID, Int32 InTargetPID, Int32 InWakeUpTID, Int32 InNativeOpti
ons, String InLibraryPath_x86, String InLibraryPath_x64, Boolean InCanBypassWOW64, Boolean InCanCreateService, Boolean I
nRequireStrongName, Object[] InPassThruArgs)
   at System.Runtime.Remoting.Messaging.StackBuilderSink._PrivateProcessMessage(IntPtr md, Object[] args, Object server,
 Object[]& outArgs)
   at System.Runtime.Remoting.Messaging.StackBuilderSink.SyncProcessMessage(IMessage msg)

Exception rethrown at [0]:
   at System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
   at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
   at EasyHook.HelperServiceInterface.InjectEx(Int32 InHostPID, Int32 InTargetPID, Int32 InWakeUpTID, Int32 InNativeOpti
ons, String InLibraryPath_x86, String InLibraryPath_x64, Boolean InCanBypassWOW64, Boolean InCanCreateService, Boolean I
nRequireStrongName, Object[] InPassThruArgs)
   at EasyHook.RemoteHooking.InjectEx(Int32 InHostPID, Int32 InTargetPID, Int32 InWakeUpTID, Int32 InNativeOptions, Stri
ng InLibraryPath_x86, String InLibraryPath_x64, Boolean InCanBypassWOW64, Boolean InCanCreateService, Boolean InRequireS
trongName, Object[] InPassThruArgs)
   at EasyHook.RemoteHooking.Inject(Int32 InTargetPID, InjectionOptions InOptions, String InLibraryPath_x86, String InLi
braryPath_x64, Object[] InPassThruArgs)
   at Program.Main(String[] args)
```

Using the latest 2.7.5726 build.

**Comment by spazzarama** [comment]
@hatRiot does the same process work with one of the examples such as "ProcessMonitor" or do you get the same issue?

**Comment by hatRiot** [comment]
Oddly enough, the `ProcessMonitor` application does not list the process as available for injection, although it is running.  `FileMon` crashes with the same error.

**Comment by spazzarama** [comment]
So the error `Unable to find EasyHook library in target process context. (Code: 5)` means that the call to LoadLibraryW within easyhook32/64.dll has failed.

@zaidalyafeai In the case of the chrome.exe processes, the ones that cannot be hooked are running as "untrusted" or with "low-rights". You can see this if you fire up Visual Studio, go to debug Attach to Process, and then check the User Name of the process you are trying to inject to.

@hatRiot could you please check your target process to see if it is running in a lower security context? Also could you please is to try running ProcessMonitor as admin (i.e. it could be the target process is running in a higher security context than ProcessMonitor).

**Comment by zaidalyafeai** [comment]
@spazzarama , you are write. I tried your suggestion chrome is correctly injected but it crashes after the injection. Any suggestion to overcome that ?

**Comment by Lalalaaaaaaa** [comment]
so how did you solve this problem finally? could you share your code @zaidalyafeai
